artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/DNA-Sequencing-Classifier/raw/master/human_data.txt
  local_data_file: artifacts/data_ingestion/human_data.txt

data_validation:
  root_dir: artifacts/data_validation
  dwn_data_file: artifacts/data_ingestion/human_data.txt
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/human_data.txt

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: best_estimator.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/best_estimator.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  cm_name: artifacts/model_evaluation/confusion_matrix.txt
